# Generated by Django 5.2.17 on 2026-09-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('planning', 'planning'), ('researching', 'researching'), ('writing', 'writing'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=20)),
                ('queries', models.JSONField(default=list)),
                ('report', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'web'), ('hn', 'hn'), ('github', 'github')], max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('snippet', models.TextField()),
                ('domain', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='research.researchrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'url'), name='unique_run_url')],
            },
        ),
    ]
